import type { Metadata } from "next";
import { Merriweather, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
// import Footer from "@/components/Footer/Footer";
import Contexts from "@/contexts/contexts";

const primaryFont = Merriweather({
  subsets: ["latin"],
  variable: "--primary-font",
  weight: ["400", "700"],
});

const secondaryFont = Roboto({
  subsets: ["latin"],
  variable: "--secondary-font",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "The Fancy Box",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Contexts>
      <html lang="en">
        <body
          className={`${primaryFont.variable} ${secondaryFont.variable} antialiased`}
        >
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="bg-black">{children}</main>

            {/* <Footer /> */}
          </div>
        </body>
      </html>
    </Contexts>
  );
}
